config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :students
  devise_for :users
  root to: "dashboard#index"
  get '/index', to: 'students#index', as: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
	require 'pdfkit'
	config.middleware.use PDFKit::Middleware
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	validates :registration_number, :uniqueness => true, :presence => true
	validates :course, :presence => true
	validates :name, :presence => true
	validates :results, :presence => true
	mount_uploader :results, ResultsUploader
end

app/models/pdfkit.rb
class Pdfkit < ApplicationRecord
	PDFKit.configure do |config|
	end
end

app/models/student.rb
class Student < ApplicationRecord
	validates :registration_number, :uniqueness => true, :presence => true
	validates :student_number, :uniqueness => true, :presence => true
	validates :name, :presence => true
	#validates :results, :presence => true
	#mount_uploader :results, ResultsUploader
	validates :bit2207, :presence => true
	validates :csc2200, :presence => true
	validates :csc2209, :presence => true
	validates :csc2210, :presence => true
	validates :csc1209, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
     respond_to do |format|
        format.html
        format.pdf do
          pdf = StudentPdf.new(@client, view_context)
          send_data pdf.render, filename: 
          "student_#{@student.created_at.strftime("%d/%m/%Y")}.pdf",
          type: "application/pdf",
          disposition: "inline"
        end
      end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :registration_number, :course, :results)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_user!
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  def index
    @students = Student.all
  end
  def show
    @student = Student.find(params[:id])
    html = render_to_string(:layout => false , :action => "show.html.erb")
    pdf = PDFKit.new(html)
    #need a button to activate the pdf download
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
      format.pdf {  send_data(pdf.to_pdf,  :filename => "#{@student.name}.pdf",
            :type => 'application/pdf', :disposition => 'inline') }
      end
  end
  def new
    @student = Student.new
  end
  def edit
  end
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end
    def student_params
      params.require(:student).permit(:registration_number, :student_number, :name, :bit2207, :csc2200, :csc2209, :csc2210, :csc1209)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>

  <div class="field">
    <%= f.label :course %>
    <%= f.text_field :course %>
  </div>

  <div class="field">
    <%= f.label :results %>
    <%= f.file_field :results %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Registration number</th>
      <th>Course</th>
      <th>Results</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.registration_number %></td>
        <td><%= client.course %></td>
        <td><%= client.results %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @client.registration_number %>
</p>

<p>
  <strong>Course:</strong>
  <%= @client.course %>
</p>

<p>
  <strong>Results:</strong>
  <%= @client.results %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/dashboard/index.html.erb
<p>Welcome to the results system admin</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Android</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
  <% if notice %>
  	<p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  	<p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class = "container" style = "padding-top:20px;">
    <%= yield %>
  <% if user_signed_in? %>
  <%= link_to 'student results', index_path %><br>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
  <% end %>
  </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>

  <div class="field">
    <%= f.label :student_number %>
    <%= f.text_field :student_number %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bit2207 %><br>
    <%= f.text_field :bit2207%>
  </div>
  <div class="field">
    <%= f.label :csc2200 %><br>
    <%= f.text_field :csc2200%>
  </div>
  <div class="field">
    <%= f.label :csc2209 %><br>
    <%= f.text_field :csc2209%>
  </div>
  <div class="field">
    <%= f.label :csc2210 %><br>
    <%= f.text_field :csc2210%>
  </div>
  <div class="field">
    <%= f.label :csc1209 %><br>
    <%= f.text_field :csc1209%>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Results</h1>

<%= link_to 'New Student', new_student_path, class: "btn btn-primary" %><br>
<br>
<br>


<table class = "table table-bordered table-striped">
  <thead>
    <tr>
      <th>Registration number</th>
      <th>Update Results</th>
      <th>Cancel Student</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.registration_number, student%></td>
        <td><%= link_to 'Update', edit_student_path(student), class: "btn btn-primary" %></td>
        <td><%= link_to 'Disqualify',  student, method: :delete, data: { confirm: 'Are you sure you want to disqualify the above student'}, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Back', root_path %><br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<h3><%= @student.name%>'s Results</h3>
<br>
<p>
  <strong>Registration number:</strong>
  <%= @student.registration_number %>
</p>

<p>
  <strong>Student number:</strong>
  <%= @student.student_number %>
</p>
<br>
<table class = "table table-bordered table-striped">
	<thead>
		<tr>
			<th>Subject</th>
			<th>Mark</th>
			<th>Credit Units</th>
			<th>Grade Point</th>
			<th>Grade</th>
			<th>Rematks</th>
		</tr>
	</thead>
	<tbody>
	<tr>
		<td>Research Methodology</td>
		<td><%= @student.bit2207 %></td>
		<td>4</td>
		<td>
			<% if @student.bit2207 >= 80 %>
			5
			<% elsif @student.bit2207 >= 75 %>
			4.5
			<% elsif @student.bit2207 >= 70 %>
			4.0
			<% elsif @student.bit2207 >= 65 %>
			3.5
			<% elsif @student.bit2207 >= 60 %>
			3.0
			<% elsif @student.bit2207 >= 55 %>
			2.5
			<% elsif @student.bit2207 >= 50 %>
			2.0
			<% elsif @student.bit2207 >= 45 %>
			1.5
			<% elsif @student.bit2207 >= 40 %>
			1.0
			<% else %>
			0.0
			<% end %>
		</td>
		<td>
			<% if @student.bit2207 >= 90 %>
			A+
			<% elsif @student.bit2207 >= 80 %>
			A
			<% elsif @student.bit2207 >= 75 %>
			B+
			<% elsif @student.bit2207 >= 70 %>
			B
			<% elsif @student.bit2207 >= 65 %>
			C+
			<% elsif @student.bit2207 >= 60 %>
			C
			<% elsif @student.bit2207 >= 55 %>
			D+
			<% elsif @student.bit2207 >= 50 %>
			D
			<% elsif @student.bit2207 >= 45 %>
			E
			<% elsif @student.bit2207 >= 40 %>
			E-
			<% else %>
			F
			<% end %>
		</td>
		<td>
			<% if @student.bit2207 >= 50 %>
			Normal
			<% else %>
			Paper to be retaken
			<% end %>
		</td>
	</tr>
	<tr>
		<td>Operating Systems</td>
		<td><%= @student.csc2200 %></td>
		<td>3</td>
		<td><% if @student.csc2200 >= 80 %>
			5.0
			<% elsif @student.csc2200 >= 75 %>
			4.5
			<% elsif @student.csc2200 >= 70 %>
			4.0
			<% elsif @student.csc2200 >= 65 %>
			3.5
			<% elsif @student.csc2200 >= 60 %>
			3.0
			<% elsif @student.csc2200 >= 55 %>
			2.5
			<% elsif @student.csc2200 >= 50 %>
			2.0
			<% elsif @student.csc2200 >= 45 %>
			1.5
			<% elsif @student.csc2200 >= 40 %>
			1.0
			<% else %>
			0.0
			<% end %></td>
		<td><% if @student.csc2200 >= 90 %>
			A+
			<% elsif @student.csc2200 >= 80 %>
			A
			<% elsif @student.csc2200 >= 75 %>
			B+
			<% elsif @student.csc2200 >= 70 %>
			B
			<% elsif @student.csc2200 >= 65 %>
			C+
			<% elsif @student.csc2200 >= 60 %>
			C
			<% elsif @student.csc2200 >= 55 %>
			D+
			<% elsif @student.csc2200 >= 50 %>
			D
			<% elsif @student.csc2200 >= 45 %>
			E
			<% elsif @student.csc2200 >= 40 %>
			E-
			<% else %>
			F
			<% end %>
		</td>
		<td>
			<% if @student.csc2200 >= 50 %>
			Normal
			<% else %>
			Paper to be retaken
			<% end %>
		</td>
	</tr>
	<tr>
		<td>Systems Programming</td>
		<td><%= @student.csc2209 %></td>
		<td>4</td>
		<td>
			<% if @student.csc2209 >= 80 %>
			5.0
			<% elsif @student.csc2209 >= 75 %>
			4.5
			<% elsif @student.csc2209 >= 70 %>
			4.0
			<% elsif @student.csc2209 >= 65 %>
			3.5
			<% elsif @student.csc2209 >= 60 %>
			3.0
			<% elsif @student.csc2209 >= 55 %>
			2.5
			<% elsif @student.csc2209 >= 50 %>
			2.0
			<% elsif @student.csc2209 >= 45 %>
			1.5
			<% elsif @student.csc2209 >= 40 %>
			1.0
			<% else %>
			0.0
			<% end %>
		</td>
		<td>
			<% if @student.csc2209 >= 90 %>
			A+
			<% elsif @student.csc2209 >= 80 %>
			A
			<% elsif @student.csc2209 >= 75 %>
			B+
			<% elsif @student.csc2209 >= 70 %>
			B
			<% elsif @student.csc2209 >= 65 %>
			C+
			<% elsif @student.csc2209 >= 60 %>
			C
			<% elsif @student.csc2209 >= 55 %>
			D+
			<% elsif @student.csc2209 >= 50 %>
			D
			<% elsif @student.csc2209 >= 45 %>
			E
			<% elsif @student.csc2209 >= 40 %>
			E-
			<% else %>
			F
			<% end %>
		</td>
		<td>
			<% if @student.csc2209 >= 50 %>
			Normal
			<% else %>
			Paper to be retaken
			<% end %>
		</td>
	</tr>
	<tr>
		<td>Automata, Complexity and Computability</td>
		<td><%= @student.csc2210 %></td>
		<td>5</td>
		<td>
			<% if @student.csc2210 >= 80 %>
			5.0
			<% elsif @student.csc2210 >= 75 %>
			4.5
			<% elsif @student.csc2210 >= 70 %>
			4.0
			<% elsif @student.csc2210 >= 65 %>
			3.5
			<% elsif @student.csc2210 >= 60 %>
			3.0
			<% elsif @student.csc2210 >= 55 %>
			2.5
			<% elsif @student.csc2210 >= 50 %>
			2.0
			<% elsif @student.csc2210 >= 45 %>
			1.5
			<% elsif @student.csc2210 >= 40 %>
			1.0
			<% else %>
			0.0
			<% end %>
		</td>
		<td>
			<% if @student.csc2210 >= 90 %>
			A+
			<% elsif @student.csc2210 >= 80 %>
			A
			<% elsif @student.csc2210 >= 75 %>
			B+
			<% elsif @student.csc2210 >= 70 %>
			B
			<% elsif @student.csc2210 >= 65 %>
			C+
			<% elsif @student.csc2210 >= 60 %>
			C
			<% elsif @student.csc2210 >= 55 %>
			D+
			<% elsif @student.csc2210 >= 50 %>
			D
			<% elsif @student.csc2210 >= 45 %>
			E
			<% elsif @student.csc2210 >= 40 %>
			E-
			<% else %>
			F
			<% end %>
		</td>
		<td>
			<% if @student.csc2210 >= 50 %>
			Normal
			<% else %>
			Paper to be retaken
			<% end %>
		</td>
	</tr>
	<tr>
		<td>Logic Programming</td>
		<td><%= @student.csc1209 %></td>
		<td>5</td>
		<td>
			<% if @student.csc1209 >= 80 %>
			5.0
			<% elsif @student.csc1209 >= 75 %>
			4.5
			<% elsif @student.csc1209 >= 70 %>
			4.0
			<% elsif @student.csc1209 >= 65 %>
			3.5
			<% elsif @student.csc1209 >= 60 %>
			3.0
			<% elsif @student.csc1209 >= 55 %>
			2.5
			<% elsif @student.csc1209 >= 50 %>
			2.0
			<% elsif @student.csc1209 >= 45 %>
			1.5
			<% elsif @student.csc1209 >= 40 %>
			1.0
			<% else %>
			0.0
			<% end %>
		</td>
		<td>
			<% if @student.csc1209 >= 90 %>
			A+
			<% elsif @student.csc1209 >= 80 %>
			A
			<% elsif @student.csc1209 >= 75 %>
			B+
			<% elsif @student.csc1209 >= 70 %>
			B
			<% elsif @student.csc1209 >= 65 %>
			C+
			<% elsif @student.csc1209 >= 60 %>
			C
			<% elsif @student.csc1209 >= 55 %>
			D+
			<% elsif @student.csc1209 >= 50 %>
			D
			<% elsif @student.csc1209 >= 45 %>
			E
			<% elsif @student.csc1209 >= 40 %>
			E-
			<% else %>
			F
			<% end %>
		</td>
		<td>
			<% if @student.csc1209 >= 50 %>
			Normal
			<% else %>
			Paper to be retaken
			<% end %>
		</td>
	</tr>
	</tbody>
</table>
<br>
<br>
<h5>Results Summary</h5>
<br>
<table class = "table table-bordered table-striped">
<thead>
	<tr><th>Cumulative Point Average</th></tr>
</thead>
<tbody>
	<tr>
		<td>CGPA will be available shortly.</td>
	</tr>
</tbody>
</table>
<br>
 <p><%= link_to "Download Results", "#{@student.id}.pdf"%></p>
 <br>
<%= link_to 'Back', students_path %>